name: Auto PR to Testing

on:
  push:
    branches:
      - 'approval_dev'
      - 'dashboard_dev'
      # Add other branches here as needed, or keep 'feature/*' if other branches follow this pattern

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "testing"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated PR to Testing from ${{ github.head_ref }}"
          pr_body: "Automatically created PR to merge changes from ${{ github.head_ref }} into testing."
